/** Declaration file generated by dts-gen */

export = isomorphic_style_loader;
declare function isomorphic_style_loader(): void;
declare namespace isomorphic_style_loader {
    function pitch(remainingRequest: any): any;
}
